# Build docs/specs/README.md from SPEC files on disk.
# Do not hand-edit the generated README.
param(
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$utf8NoBom = New-Object System.Text.UTF8Encoding $false

function Get-RepoRoot {
    $root = (git rev-parse --show-toplevel).Trim()
    if (-not $root) { throw "not inside a git work tree" }
    return $root
}

function Get-SpecTitle([string]$path, [string]$id) {
    $lines = [System.IO.File]::ReadAllLines($path, [System.Text.Encoding]::UTF8)
    foreach ($raw in $lines) {
        $line = $raw.Trim()
        if ($line -match '^#\s+') {
            $heading = $line -replace '^#\s+', ''
            if ($heading -match "^spec-$([regex]::Escape($id)):\s*(.+)$") {
                return $Matches[1].Trim()
            }
            if ($heading -match '^SPEC:\s*(.+)$') {
                return $Matches[1].Trim()
            }
            if ($heading -match '^spec-[a-z0-9-]+:\s*(.+)$') {
                return $Matches[1].Trim()
            }
            return $heading
        }
    }
    return $id
}

function Escape-Cell([string]$text) {
    return ($text -replace '\r?\n', ' ' -replace '\|', '\|').Trim()
}

function Build-IndexMarkdown([string]$specsRoot) {
    $statusOrder = @(
        'DRAFT',
        'IN-PROGRESS',
        'DONE',
        'DONE-REFACTORED',
        'SUPERSEDED',
        'ARCHIVED',
        'OBSOLETE'
    )
    $headerOf = @{
        'DRAFT'            = 'draft'
        'IN-PROGRESS'      = 'in-progress'
        'DONE'             = 'done'
        'DONE-REFACTORED'  = 'done-refactored'
        'SUPERSEDED'       = 'superseded'
        'ARCHIVED'         = 'archived'
        'OBSOLETE'         = 'obsolete'
    }

    $pattern = '^spec-(.+)\[(' + ($statusOrder -join '|') + ')\]\.md$'
    $specs = @()
    Get-ChildItem -LiteralPath $specsRoot -Directory | ForEach-Object {
        $area = $_.Name
        Get-ChildItem -LiteralPath $_.FullName -File -Filter 'spec-*.md' | ForEach-Object {
            if ($_.Name -notmatch $pattern) {
                Write-Warning "skip unrecognized SPEC filename: $($area)/$($_.Name)"
                return
            }
            $id = $Matches[1]
            $tag = $Matches[2]
            $specs += [pscustomobject]@{
                Id     = $id
                Tag    = $tag
                Status = $headerOf[$tag]
                Area   = $area
                File   = $_.Name
                Title  = Get-SpecTitle $_.FullName $id
            }
        }
    }

    $specs = @($specs | Sort-Object Area, Id)
    $total = $specs.Count
    $counts = @{}
    foreach ($tag in $statusOrder) { $counts[$tag] = 0 }
    foreach ($s in $specs) { $counts[$s.Tag]++ }

    $areas = @(
        $specs |
            Group-Object Area |
            Sort-Object Name |
            ForEach-Object { [pscustomobject]@{ Name = $_.Name; Count = $_.Count } }
    )

    $active = @($specs | Where-Object { $_.Tag -in @('DRAFT', 'IN-PROGRESS') })
    $tick = '`'

    $genMark = '<' + '!-- Generated by scripts/build-spec-index.ps1. Do not edit. --' + '>'
    $scanPat = 'docs/specs/<area>/spec-*' + '[STATUS]' + '.md'
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('# 功能规格文档（SPEC）')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine($genMark)
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine(('本文件由脚本扫描 ' + $tick + $scanPat + $tick + ' 生成，只反映磁盘上的 SPEC 数量与状态。'))
    [void]$sb.AppendLine('命名、状态机、area 规则见 [`docs/rules/docs-conventions.md`](../rules/docs-conventions.md)。')
    [void]$sb.AppendLine('类型边界见 [`docs/rules/rule-doc-boundary.md`](../rules/rule-doc-boundary.md)。')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('不要手改本文件。SPEC 新增、改名或改状态后运行：')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('```text')
    [void]$sb.AppendLine('powershell -File scripts/build-spec-index.ps1')
    [void]$sb.AppendLine('```')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('## 统计')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("| 状态 | 数量 |")
    [void]$sb.AppendLine("| :--- | ---: |")
    foreach ($tag in $statusOrder) {
        [void]$sb.AppendLine("| $tick$($headerOf[$tag])$tick | $($counts[$tag]) |")
    }
    [void]$sb.AppendLine("| 合计 | $total |")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('## Area')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('| Area | SPEC 数 |')
    [void]$sb.AppendLine('| :--- | ---: |')
    foreach ($a in $areas) {
        [void]$sb.AppendLine("| [$tick$($a.Name)/$tick](./$($a.Name)/) | $($a.Count) |")
    }
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('## 进行中')
    [void]$sb.AppendLine('')
    if ($active.Count -eq 0) {
        [void]$sb.AppendLine('无 `[DRAFT]` / `[IN-PROGRESS]` SPEC。')
        [void]$sb.AppendLine('')
    } else {
        [void]$sb.AppendLine('| SPEC | Area | 主题 | 状态 |')
        [void]$sb.AppendLine('| :--- | :--- | :--- | :--- |')
        foreach ($s in $active) {
            $title = Escape-Cell $s.Title
            [void]$sb.AppendLine("| [spec-$($s.Id)](./$($s.Area)/$($s.File)) | $($s.Area) | $title | $tick$($s.Status)$tick |")
        }
        [void]$sb.AppendLine('')
    }
    [void]$sb.AppendLine('## 索引')
    [void]$sb.AppendLine('')
    foreach ($group in ($specs | Group-Object Area | Sort-Object Name)) {
        [void]$sb.AppendLine("### [$($group.Name)/](./$($group.Name)/)")
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('| SPEC | 主题 | 状态 |')
        [void]$sb.AppendLine('| :--- | :--- | :--- |')
        foreach ($s in @($group.Group | Sort-Object Id)) {
            $title = Escape-Cell $s.Title
            [void]$sb.AppendLine("| [spec-$($s.Id)](./$($s.Area)/$($s.File)) | $title | $tick$($s.Status)$tick |")
        }
        [void]$sb.AppendLine('')
    }
    return $sb.ToString() -replace "`r`n", "`n" -replace "`r", "`n"
}

$root = Get-RepoRoot
$specsRoot = Join-Path $root "docs\specs"
$readmePath = Join-Path $specsRoot "README.md"
$generated = Build-IndexMarkdown $specsRoot
if (-not $generated.EndsWith("`n")) { $generated += "`n" }

if ($Check) {
    if (-not (Test-Path -LiteralPath $readmePath)) {
        Write-Error "missing $readmePath"
        exit 1
    }
    $existing = [System.IO.File]::ReadAllText($readmePath) -replace "`r`n", "`n" -replace "`r", "`n"
    if ($existing -ne $generated) {
        Write-Error "docs/specs/README.md is stale. Run: powershell -File scripts/build-spec-index.ps1"
        exit 1
    }
    Write-Host "docs/specs/README.md is up to date."
    exit 0
}

[System.IO.File]::WriteAllText($readmePath, $generated, $utf8NoBom)
Write-Host "Wrote $readmePath"
